<?php
/**
 * Class which returns the class map definition
 * @package
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get()
    {
        return array(
            'ClientDataItem' => '\\StructType\\ClientDataItem',
            'Account' => '\\StructType\\Account',
            'BillSplit' => '\\StructType\\BillSplit',
            'Document' => '\\StructType\\Document',
            'Note' => '\\StructType\\Note',
            'AbstractDocumentHolder' => '\\StructType\\AbstractDocumentHolder',
            'CustomField' => '\\StructType\\CustomField',
            'Contact' => '\\StructType\\Contact',
            'Vendor' => '\\StructType\\Vendor',
            'VendorType' => '\\StructType\\VendorType',
            'CreditMemo' => '\\StructType\\CreditMemo',
            'Payment' => '\\StructType\\Payment',
            'AbstractFinancialDocumentHolder' => '\\StructType\\AbstractFinancialDocumentHolder',
            'BillPayment' => '\\StructType\\BillPayment',
            'JournalEntry' => '\\StructType\\JournalEntry',
            'Nsf' => '\\StructType\\Nsf',
            'AbstractCustomizableSystemId' => '\\StructType\\AbstractCustomizableSystemId',
            'VMMLeaseCharge' => '\\StructType\\VMMLeaseCharge',
            'Bill' => '\\StructType\\Bill',
            'LineItem' => '\\StructType\\LineItem',
            'Refund' => '\\StructType\\Refund',
            'BankDeposit' => '\\StructType\\BankDeposit',
            'Charge' => '\\StructType\\Charge',
            'Check' => '\\StructType\\Check',
            'PaymentMethod' => '\\StructType\\PaymentMethod',
            'FinancialTransaction' => '\\StructType\\FinancialTransaction',
            'LedgerItem' => '\\StructType\\LedgerItem',
            'OwnerLedgerItem' => '\\StructType\\OwnerLedgerItem',
            'Bank' => '\\StructType\\Bank',
            'Portfolio' => '\\StructType\\Portfolio',
            'OwnerDraw' => '\\StructType\\OwnerDraw',
            'Item' => '\\StructType\\Item',
            'Unit' => '\\StructType\\Unit',
            'BuildingInsuranceCarrier' => '\\StructType\\BuildingInsuranceCarrier',
            'ManagementFee' => '\\StructType\\ManagementFee',
            'Building' => '\\StructType\\Building',
            'SyncGroup' => '\\StructType\\SyncGroup',
            'Activity' => '\\StructType\\Activity',
            'Owner' => '\\StructType\\Owner',
            'User' => '\\StructType\\User',
            'AutoCharge' => '\\StructType\\AutoCharge',
            'LateFeeRule' => '\\StructType\\LateFeeRule',
            'EmploymentHistory' => '\\StructType\\EmploymentHistory',
            'Applicant' => '\\StructType\\Applicant',
            'Lease' => '\\StructType\\Lease',
            'WorkOrder' => '\\StructType\\WorkOrder',
            'Budget' => '\\StructType\\Budget',
            'LeaseLedgerItem' => '\\StructType\\LeaseLedgerItem',
            'FinancialTransactionHeader' => '\\StructType\\FinancialTransactionHeader',
            'JournalEntryHeader' => '\\StructType\\JournalEntryHeader',
            'LeaseJournalEntry' => '\\StructType\\LeaseJournalEntry',
            'LeaseJournalEntryDetail' => '\\StructType\\LeaseJournalEntryDetail',
            'LeaseAppliedToChargeItem' => '\\StructType\\LeaseAppliedToChargeItem',
            'LeaseCharge' => '\\StructType\\LeaseCharge',
            'LeasePayment' => '\\StructType\\LeasePayment',
            'LeaseAppliedPaymentItem' => '\\StructType\\LeaseAppliedPaymentItem',
            'LeasePaymentDetail' => '\\StructType\\LeasePaymentDetail',
            'LeasePrepaymentDetail' => '\\StructType\\LeasePrepaymentDetail',
            'LeaseDiscount' => '\\StructType\\LeaseDiscount',
            'LeaseAppliedDiscount' => '\\StructType\\LeaseAppliedDiscount',
            'LeaseCredit' => '\\StructType\\LeaseCredit',
            'LeaseCreditDetail' => '\\StructType\\LeaseCreditDetail',
            'LeaseRefund' => '\\StructType\\LeaseRefund',
            'VendorLedgerItem' => '\\StructType\\VendorLedgerItem',
            'VendorBill' => '\\StructType\\VendorBill',
            'VendorBillPayment' => '\\StructType\\VendorBillPayment',
            'VendorBillPaymentDetail' => '\\StructType\\VendorBillPaymentDetail',
            'VendorBillDetail' => '\\StructType\\VendorBillDetail',
            'OwnerJournalEntry' => '\\StructType\\OwnerJournalEntry',
            'OwnerJournalEntryDetail' => '\\StructType\\OwnerJournalEntryDetail',
            'OwnerContribution' => '\\StructType\\OwnerContribution',
            'DepositTicket' => '\\StructType\\DepositTicket',
            'LeaseSearchCriteria' => '\\StructType\\LeaseSearchCriteria',
            'BuildingSearchCriteria' => '\\StructType\\BuildingSearchCriteria',
            'WorkOrderSearchCriteria' => '\\StructType\\WorkOrderSearchCriteria',
            'UnitSearchCriteria' => '\\StructType\\UnitSearchCriteria',
            'CampaignSource' => '\\StructType\\CampaignSource',
            'Campaign' => '\\StructType\\Campaign',
            'Prospect' => '\\StructType\\Prospect',
            'CampaignSearchCriteria' => '\\StructType\\CampaignSearchCriteria',
            'CustomFieldDefinition' => '\\StructType\\CustomFieldDefinition',
            'AppointmentSearchCriteria' => '\\StructType\\AppointmentSearchCriteria',
            'Appointment' => '\\StructType\\Appointment',
            'ContactSearchCriteria' => '\\StructType\\ContactSearchCriteria',
            'ProspectSearchCriteria' => '\\StructType\\ProspectSearchCriteria',
            'Task' => '\\StructType\\Task',
            'TaskList' => '\\StructType\\TaskList',
            'OwnerSearchCriteria' => '\\StructType\\OwnerSearchCriteria',
            'Ledger' => '\\StructType\\Ledger',
            'OwnerLedger' => '\\StructType\\OwnerLedger',
            'LeaseLedger' => '\\StructType\\LeaseLedger',
            'VendorLedger' => '\\StructType\\VendorLedger',
            'PropertyManager' => '\\StructType\\PropertyManager',
            'UserActivity' => '\\StructType\\UserActivity',
            'ReadOnlyLeaseLedgerSearchCriteria' => '\\StructType\\ReadOnlyLeaseLedgerSearchCriteria',
            'ReadOnlyFinancialTransaction' => '\\StructType\\ReadOnlyFinancialTransaction',
            'ReadOnlyLedgerItem' => '\\StructType\\ReadOnlyLedgerItem',
            'ReadOnlyLedger' => '\\StructType\\ReadOnlyLedger',
            'ReadOnlyLeaseLedger' => '\\StructType\\ReadOnlyLeaseLedger',
            'ReadOnlyLeaseLedgerItem' => '\\StructType\\ReadOnlyLeaseLedgerItem',
            'ReadOnlyLeaseCharge' => '\\StructType\\ReadOnlyLeaseCharge',
            'ReadOnlyLeaseCredit' => '\\StructType\\ReadOnlyLeaseCredit',
            'ReadOnlyLeaseDiscount' => '\\StructType\\ReadOnlyLeaseDiscount',
            'ReadOnlyLeaseJournalEntryDetail' => '\\StructType\\ReadOnlyLeaseJournalEntryDetail',
            'ReadOnlyLeaseJournalEntry' => '\\StructType\\ReadOnlyLeaseJournalEntry',
            'ReadOnlyLeasePayment' => '\\StructType\\ReadOnlyLeasePayment',
            'ReadOnlyLeaseRefund' => '\\StructType\\ReadOnlyLeaseRefund',
            'Inspection' => '\\StructType\\Inspection',
            'BudgetSearchCriteria' => '\\StructType\\BudgetSearchCriteria',
            'BillSearchCriteria' => '\\StructType\\BillSearchCriteria',
            'ReadOnlyVendorLedgerSearchCriteria' => '\\StructType\\ReadOnlyVendorLedgerSearchCriteria',
            'ReadOnlyVendorLedger' => '\\StructType\\ReadOnlyVendorLedger',
            'ReadOnlyVendorLedgerItem' => '\\StructType\\ReadOnlyVendorLedgerItem',
            'ReadOnlyVendorLedgerBillSplit' => '\\StructType\\ReadOnlyVendorLedgerBillSplit',
            'ReadOnlyVendorLedgerBill' => '\\StructType\\ReadOnlyVendorLedgerBill',
            'ReadOnlyVendorLedgerBillPayment' => '\\StructType\\ReadOnlyVendorLedgerBillPayment',
            'ReadOnlyVendorLedgerCheck' => '\\StructType\\ReadOnlyVendorLedgerCheck',
            'EPayInfo' => '\\StructType\\EPayInfo',
            'InspectionSearchCriteria' => '\\StructType\\InspectionSearchCriteria',
            'InspectionItem' => '\\StructType\\InspectionItem',
            'InspectionArea' => '\\StructType\\InspectionArea',
            'LeasingAgent' => '\\StructType\\LeasingAgent',
            'ReportSetting' => '\\StructType\\ReportSetting',
            'ReportConfiguration' => '\\StructType\\ReportConfiguration',
            'Customer' => '\\StructType\\Customer',
            'Tenant' => '\\StructType\\Tenant',
            'PropertyPhoto' => '\\StructType\\PropertyPhoto',
            'Report' => '\\StructType\\Report',
            'ClientDataContainer' => '\\StructType\\ClientDataContainer',
            'PWObject' => '\\StructType\\PWObject',
            'PWFinanceObject' => '\\StructType\\PWFinanceObject',
            'AbstractCustomizableDTO' => '\\StructType\\AbstractCustomizableDTO',
            'Vector' => '\\StructType\\Vector',
            'BaseDTOSearchCriteria' => '\\StructType\\BaseDTOSearchCriteria',
            'AuditableDTOSearchCriteria' => '\\StructType\\AuditableDTOSearchCriteria',
        );
    }
}
